/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.UserDao;
import fn.Boton;
import fn.FnCliente;
import fn.FnFicha;
import fn.FnInfo;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Lenovo G470
 */
public class ContentAdmin extends javax.swing.JFrame {

    Boton boton = new Boton();
    FnInfo load = new FnInfo();
    public static JTextField idSesion = new JTextField();
    public static String version = "v3.2.0";
    
    private void cerrar() throws SQLException, ClassNotFoundException{
        String botones1[] = {"Cerrar","Cancelar"};
        int opcion = JOptionPane.showOptionDialog(this, "¿Desea cerrar la aplicación?", "Cerrar", 0, 0, null, botones1, this);
        if(opcion == JOptionPane.YES_OPTION){
            String botones2[] = {"Aceptar","Anular"};
            if(load.isConnected()){
                opcion = JOptionPane.showOptionDialog(this, "Se respaldará la base de datos", "Respaldar", 0, 0, null, botones2, this);
                if(opcion == JOptionPane.YES_OPTION){
                    try{
                        if(load.isActive()){
                            new Splash().setVisible(true);
                            load.crearBackUp("sdxod", "root", load.getDbPass());
                        }else
                           JOptionPane.showMessageDialog(null,"No se pueden respaldar los datos,\ntoda la información se puede perder si no renueva su licencia.","Es necesaria la renovación de la Licencia",JOptionPane.WARNING_MESSAGE); 
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, "No se pudo ejecutar el respaldo","Error",JOptionPane.WARNING_MESSAGE);
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"La información valiosa del sistema podría perderse para siempre.\nHaga respaldo de datos periódicamente por su seguridad.","Es necesario respaldar la base de datos",JOptionPane.WARNING_MESSAGE); 
                }
            }
            
            System.exit(0);
        }   
    }
    /**
     * Creates new form ContentAdmin
     * @throws java.sql.SQLException
     * @throws java.lang.ClassNotFoundException
     */
    public ContentAdmin() throws SQLException, ClassNotFoundException{
        initComponents();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        iniciar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        mnpnlPlantas = new javax.swing.JPanel();
        btnClientes = new javax.swing.JButton();
        btnDoctores = new javax.swing.JButton();
        btnInstituciones = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mnpnlVentas = new javax.swing.JPanel();
        btnNuevaFicha = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnMisRegistros = new javax.swing.JButton();
        principalAdmin = new javax.swing.JPanel();
        mnpnlRegistros = new javax.swing.JPanel();
        imgLogoEmpresa = new javax.swing.JLabel();
        sesion = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuCargarFicha = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnuCristales = new javax.swing.JMenuItem();
        mnuArmazones = new javax.swing.JMenuItem();
        mnuRegistroBajas = new javax.swing.JMenuItem();
        mnuExportarInventario = new javax.swing.JMenuItem();
        mnuOC = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        mnuUsuarios = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        mnpnlPlantas.setBackground(new java.awt.Color(255, 255, 255));
        mnpnlPlantas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 0, 11), new java.awt.Color(0, 51, 51))); // NOI18N

        btnClientes.setBackground(new java.awt.Color(153, 255, 153));
        btnClientes.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(0, 102, 0));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault1.jpg"))); // NOI18N
        btnClientes.setBorder(null);
        btnClientes.setBorderPainted(false);
        btnClientes.setContentAreaFilled(false);
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClientes.setIconTextGap(-3);
        btnClientes.setLabel("Clientes");
        btnClientes.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault3.jpg"))); // NOI18N
        btnClientes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault2.jpg"))); // NOI18N
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnDoctores.setBackground(new java.awt.Color(153, 255, 153));
        btnDoctores.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        btnDoctores.setForeground(new java.awt.Color(0, 102, 0));
        btnDoctores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault1.jpg"))); // NOI18N
        btnDoctores.setBorder(null);
        btnDoctores.setBorderPainted(false);
        btnDoctores.setContentAreaFilled(false);
        btnDoctores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDoctores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDoctores.setIconTextGap(-3);
        btnDoctores.setLabel("Doctores");
        btnDoctores.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault3.jpg"))); // NOI18N
        btnDoctores.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault2.jpg"))); // NOI18N
        btnDoctores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctoresActionPerformed(evt);
            }
        });

        btnInstituciones.setBackground(new java.awt.Color(153, 255, 153));
        btnInstituciones.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        btnInstituciones.setForeground(new java.awt.Color(0, 102, 0));
        btnInstituciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault1.jpg"))); // NOI18N
        btnInstituciones.setBorder(null);
        btnInstituciones.setBorderPainted(false);
        btnInstituciones.setContentAreaFilled(false);
        btnInstituciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInstituciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInstituciones.setIconTextGap(-3);
        btnInstituciones.setLabel("Instituciones");
        btnInstituciones.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault3.jpg"))); // NOI18N
        btnInstituciones.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault2.jpg"))); // NOI18N
        btnInstituciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstitucionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mnpnlPlantasLayout = new javax.swing.GroupLayout(mnpnlPlantas);
        mnpnlPlantas.setLayout(mnpnlPlantasLayout);
        mnpnlPlantasLayout.setHorizontalGroup(
            mnpnlPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mnpnlPlantasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mnpnlPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInstituciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDoctores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        mnpnlPlantasLayout.setVerticalGroup(
            mnpnlPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mnpnlPlantasLayout.createSequentialGroup()
                .addComponent(btnClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDoctores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInstituciones, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Optidata "+ContentAdmin.version, javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 0, 11), new java.awt.Color(102, 102, 102)));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Soporte Técnico:");

        jLabel7.setText("  www.softdirex.cl");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(imgLogo))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7))
        );

        mnpnlVentas.setBackground(new java.awt.Color(255, 255, 255));
        mnpnlVentas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fichas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 0, 11), new java.awt.Color(0, 51, 51))); // NOI18N

        btnNuevaFicha.setBackground(new java.awt.Color(153, 255, 153));
        btnNuevaFicha.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        btnNuevaFicha.setForeground(new java.awt.Color(0, 102, 0));
        btnNuevaFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault1.jpg"))); // NOI18N
        btnNuevaFicha.setBorder(null);
        btnNuevaFicha.setBorderPainted(false);
        btnNuevaFicha.setContentAreaFilled(false);
        btnNuevaFicha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevaFicha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevaFicha.setIconTextGap(-3);
        btnNuevaFicha.setLabel("Nueva");
        btnNuevaFicha.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault3.jpg"))); // NOI18N
        btnNuevaFicha.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault2.jpg"))); // NOI18N
        btnNuevaFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaFichaActionPerformed(evt);
            }
        });

        btnListar.setBackground(new java.awt.Color(153, 255, 153));
        btnListar.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        btnListar.setForeground(new java.awt.Color(0, 102, 0));
        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault1.jpg"))); // NOI18N
        btnListar.setText("Fichas");
        btnListar.setBorder(null);
        btnListar.setBorderPainted(false);
        btnListar.setContentAreaFilled(false);
        btnListar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnListar.setIconTextGap(-3);
        btnListar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault3.jpg"))); // NOI18N
        btnListar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault2.jpg"))); // NOI18N
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnMisRegistros.setBackground(new java.awt.Color(153, 255, 153));
        btnMisRegistros.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        btnMisRegistros.setForeground(new java.awt.Color(0, 102, 0));
        btnMisRegistros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault1.jpg"))); // NOI18N
        btnMisRegistros.setText("Mis ventas");
        btnMisRegistros.setBorder(null);
        btnMisRegistros.setBorderPainted(false);
        btnMisRegistros.setContentAreaFilled(false);
        btnMisRegistros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMisRegistros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMisRegistros.setIconTextGap(-3);
        btnMisRegistros.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault3.jpg"))); // NOI18N
        btnMisRegistros.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault2.jpg"))); // NOI18N
        btnMisRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMisRegistrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mnpnlVentasLayout = new javax.swing.GroupLayout(mnpnlVentas);
        mnpnlVentas.setLayout(mnpnlVentasLayout);
        mnpnlVentasLayout.setHorizontalGroup(
            mnpnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNuevaFicha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mnpnlVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mnpnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMisRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        mnpnlVentasLayout.setVerticalGroup(
            mnpnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mnpnlVentasLayout.createSequentialGroup()
                .addComponent(btnNuevaFicha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(btnMisRegistros))
        );

        btnNuevaFicha.getAccessibleContext().setAccessibleDescription("");

        principalAdmin.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout principalAdminLayout = new javax.swing.GroupLayout(principalAdmin);
        principalAdmin.setLayout(principalAdminLayout);
        principalAdminLayout.setHorizontalGroup(
            principalAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1048, Short.MAX_VALUE)
        );
        principalAdminLayout.setVerticalGroup(
            principalAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        mnpnlRegistros.setBackground(new java.awt.Color(255, 255, 255));
        mnpnlRegistros.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 0, 11), new java.awt.Color(0, 51, 51))); // NOI18N

        imgLogoEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo3.png"))); // NOI18N

        javax.swing.GroupLayout mnpnlRegistrosLayout = new javax.swing.GroupLayout(mnpnlRegistros);
        mnpnlRegistros.setLayout(mnpnlRegistrosLayout);
        mnpnlRegistrosLayout.setHorizontalGroup(
            mnpnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(mnpnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnpnlRegistrosLayout.createSequentialGroup()
                    .addContainerGap(23, Short.MAX_VALUE)
                    .addComponent(imgLogoEmpresa)
                    .addGap(28, 28, 28)))
        );
        mnpnlRegistrosLayout.setVerticalGroup(
            mnpnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 141, Short.MAX_VALUE)
            .addGroup(mnpnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mnpnlRegistrosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(imgLogoEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        sesion.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mnpnlPlantas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mnpnlRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mnpnlVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sesion)
                        .addGap(52, 52, 52)))
                .addComponent(principalAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(mnpnlVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mnpnlPlantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mnpnlRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sesion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(principalAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("\"OptiData \"+ContentAdmin.version");
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N

        jMenu1.setText("Archivo");

        mnuCargarFicha.setText("Cargar por folio");
        mnuCargarFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCargarFichaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCargarFicha);

        jMenuItem4.setText("Respaldar datos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Herramientas");

        jMenu3.setText("Exportar correos");

        jMenuItem7.setText("Todos los clientes");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem6.setText("Clientes morosos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem3.setText("Lentes cancelados sin retirar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenu4.add(jMenu3);

        jMenuItem8.setText("Reporte de ventas");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Inventario");

        mnuCristales.setText("Cristales");
        mnuCristales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCristalesActionPerformed(evt);
            }
        });
        jMenu5.add(mnuCristales);

        mnuArmazones.setText("Armazones");
        mnuArmazones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArmazonesActionPerformed(evt);
            }
        });
        jMenu5.add(mnuArmazones);

        mnuRegistroBajas.setText("Registro de bajas");
        mnuRegistroBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegistroBajasActionPerformed(evt);
            }
        });
        jMenu5.add(mnuRegistroBajas);

        mnuExportarInventario.setText("Exportar inventario");
        mnuExportarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExportarInventarioActionPerformed(evt);
            }
        });
        jMenu5.add(mnuExportarInventario);

        mnuOC.setText("Generar orden de compra");
        mnuOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOCActionPerformed(evt);
            }
        });
        jMenu5.add(mnuOC);

        jMenuBar1.add(jMenu5);

        jMenu2.setBackground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("Configuración");

        jMenuItem9.setText("Datos empresa");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        mnuUsuarios.setText("Usuarios");
        mnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsuariosActionPerformed(evt);
            }
        });
        jMenu2.add(mnuUsuarios);

        jMenuItem10.setText("Tipos de pago");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuItem11.setText("Descuentos");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem2.setText("Sincronizar folio");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void btnNuevaFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaFichaActionPerformed
        try {
            boton.nuevaFicha();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ContentAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNuevaFichaActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        FnFicha load = new FnFicha();
        try {
            Date d1 = new Date();
            boton.fichas(load.listarPorFecha(d1,d1));
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ContentAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        try {
            boton.clientes();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ContentAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnDoctoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctoresActionPerformed
        try {
            boton.doctores();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ContentAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDoctoresActionPerformed

    private void btnInstitucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstitucionesActionPerformed
        try {
            boton.instituciones();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ContentAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInstitucionesActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        FnCliente load = new FnCliente();
        try {
            load.guardarCorreos();
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error inesperado "+ex.getMessage(), "Guardar correos", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        try {
            boton.datosEmpresa();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ContentAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        if(validarAdmin()){
            try {
                boton.tipoPago();
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(ContentAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        if(validarAdmin()){    
            try {
                boton.descuentos();
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(ContentAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if(validarAdmin()){
            FnInfo load = new FnInfo();
            String respuesta;
            try {
                respuesta = JOptionPane.showInputDialog("Ingrese el siguiente folio",""+load.obtenerFolio());
                if(respuesta == null)
                    return;
                String resp = load.actualizarFolio(respuesta,load.obtenerFolio());
                JOptionPane.showMessageDialog(null, resp,"Actualizar Folio",JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException | ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Error inesperado: "+ex.getMessage(),"Actualizar Folio",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        FnCliente load = new FnCliente();
        try {
            load.guardarCorreosMorosos();
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error inesperado "+ex.getMessage(), "Guardar correos", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        FnCliente load = new FnCliente();
        try {
            load.guardarCorreosSinRetirar();
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error inesperado "+ex.getMessage(), "Guardar correos", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        if(load.isActive()){
            new Splash().setVisible(true);
            try {
                
                load.crearBackUp("sdxod", "root", load.getDbPass());
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(ContentAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null,"No se pueden respaldar los datos,\ntoda la información se puede perder si no renueva su licencia.","Es necesaria la renovación de la Licencia",JOptionPane.WARNING_MESSAGE);
        }
        
            
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void mnuCristalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCristalesActionPerformed
        JPasswordField pwd = new JPasswordField(10);
        int res = JOptionPane.showConfirmDialog(null,pwd, "Ingrese clave de inventario",JOptionPane.OK_CANCEL_OPTION);
        if(res < 0){
            
            return;
        }else{
            if(res == 2)
                return;
            String respuesta = pwd.getText();
            UserDao load = new UserDao();
            try {
                if(load.ingresar(respuesta)){
                    boton.cristales();
                }
            } catch (SQLException | ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Error inesperado: "+ex.getMessage(),"Acceso",JOptionPane.WARNING_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_mnuCristalesActionPerformed

    private void mnuArmazonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArmazonesActionPerformed
        JPasswordField pwd = new JPasswordField(10);
        int res = JOptionPane.showConfirmDialog(null,pwd, "Ingrese clave de inventario",JOptionPane.OK_CANCEL_OPTION);
        if(res < 0){
            
            return;
        }else{
            if(res == 2)
                return;
            String respuesta = pwd.getText();
            UserDao load = new UserDao();
            try {
                if(load.ingresar(respuesta)){
                    boton.lentes();
                }
            } catch (SQLException | ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Error inesperado: "+ex.getMessage(),"Acceso",JOptionPane.WARNING_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_mnuArmazonesActionPerformed

    private void mnuRegistroBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegistroBajasActionPerformed
        JPasswordField pwd = new JPasswordField(10);
        int res = JOptionPane.showConfirmDialog(null,pwd, "Ingrese clave de inventario",JOptionPane.OK_CANCEL_OPTION);
        if(res < 0){
            
            return;
        }else{
            if(res == 2)
                return;
            String respuesta = pwd.getText();
            UserDao load = new UserDao();
            try {
                if(load.ingresar(respuesta)){
                    boton.registroBajas();
                }
            } catch (SQLException | ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Error inesperado: "+ex.getMessage(),"Acceso",JOptionPane.WARNING_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_mnuRegistroBajasActionPerformed

    private void mnuOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOCActionPerformed
        try {
            load.generarOrdenCompra();
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error inesperado "+ex.getMessage(), "Guardar correos", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_mnuOCActionPerformed

    private void mnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuariosActionPerformed
        if(validarAdmin()){
            try {
                boton.usuarios();
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(ContentAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_mnuUsuariosActionPerformed

    private void mnuExportarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExportarInventarioActionPerformed
        if(validarAdmin()){
            try {
                load.exportarInventario();
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(ContentAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_mnuExportarInventarioActionPerformed

    private void btnMisRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMisRegistrosActionPerformed
        try {
            boton.misFichas();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ContentAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMisRegistrosActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        if(load.isActive()){
            if(validarAdmin()){
                try {
                    boton.reporteVentas();
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(ContentAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }else{
            JOptionPane.showMessageDialog(null,"No se pueden generar reportes,\nLa licencia del producto se encuentra obsoleta.","Es necesaria la renovación de la Licencia",JOptionPane.INFORMATION_MESSAGE);
        }   
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void mnuCargarFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCargarFichaActionPerformed
        JTextField idFicha = new JTextField();
        int res = JOptionPane.showConfirmDialog(null,idFicha, "Ingrese numero de folio",JOptionPane.OK_CANCEL_OPTION);
        if(res < 0){
            return;
        }else{
            if(res == 2)
                return;
            String respuesta = idFicha.getText();
            FnInfo load = new FnInfo();
            try {
                Boton btn = new Boton();
                btn.abrirFicha(respuesta);
        }catch (SQLException | ClassNotFoundException | NullPointerException ex) {
                JOptionPane.showMessageDialog(null, "Error: El folio ingresado no existe.","Error",JOptionPane.WARNING_MESSAGE);
            }
        }
        return;
    }//GEN-LAST:event_mnuCargarFichaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            cerrar();
        } catch (SQLException ex) {
            Logger.getLogger(ContentAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ContentAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContentAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContentAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContentAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContentAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ContentAdmin().setVisible(true);
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(ContentAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnDoctores;
    private javax.swing.JButton btnInstituciones;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnMisRegistros;
    private javax.swing.JButton btnNuevaFicha;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel imgLogoEmpresa;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mnpnlPlantas;
    private javax.swing.JPanel mnpnlRegistros;
    private javax.swing.JPanel mnpnlVentas;
    private javax.swing.JMenuItem mnuArmazones;
    private javax.swing.JMenuItem mnuCargarFicha;
    private javax.swing.JMenuItem mnuCristales;
    private javax.swing.JMenuItem mnuExportarInventario;
    private javax.swing.JMenuItem mnuOC;
    private javax.swing.JMenuItem mnuRegistroBajas;
    private javax.swing.JMenuItem mnuUsuarios;
    public static javax.swing.JPanel principalAdmin;
    public static javax.swing.JLabel sesion;
    // End of variables declaration//GEN-END:variables

    private void centrarPantalla() {
        this.setLocationRelativeTo(null);
    }
    
    public void setIdSesion (int id) throws SQLException, ClassNotFoundException
   {
      this.idSesion.setText(""+id);
      sesion.setText(""+id);
      iniciar();
   }

    private void entrar() throws SQLException, ClassNotFoundException {
        try {
            boton.nuevaFicha();
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Es probable que el servidor no se haya iniciado, Inicie el servicio y vuelva a abrir el programa.","Error de conexion",JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
    }

    private boolean validarAdmin() {
        JPasswordField pwd = new JPasswordField(10);
        int res = JOptionPane.showConfirmDialog(null,pwd, "Ingrese clave de administrador",JOptionPane.OK_CANCEL_OPTION);
        if(res < 0){
            return false;
        }else{
            if(res == 2)
                return false;
            String respuesta = pwd.getText();
            FnInfo load = new FnInfo();
            try {
                if(respuesta.equals(load.getPass())){
                    return true;
                }else
                    JOptionPane.showMessageDialog(null, "La contraseña es incorrecta","Acceso denegado",JOptionPane.ERROR_MESSAGE);
        }catch (SQLException | ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Error: "+ex.getMessage(),"Error",JOptionPane.WARNING_MESSAGE);
            }
        }
        return false;
    }

    private void iniciar() throws SQLException, ClassNotFoundException {
        load.probarConexion();
        centrarPantalla();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/icon.png"));
        setIconImage(icon);
        String licencia;
        if(load.isActive())
            licencia = "Producto bajo licencia hasta el "+load.cargarFechaLicencia();
        else
            licencia = "La licencia de este producto ha caducado";
        this.setTitle("Optidata "+version+"     "+licencia);
        sesion.setVisible(false);
        entrar();
    }

}
