/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entities.Cliente;
import entities.Despacho;
import entities.Ficha;
import entities.HistorialPago;
import entities.TipoPago;
import fn.Boton;
import fn.FnCliente;
import fn.FnFicha;
import fn.FnNuevaFicha;
import fn.FnValidaRut;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author home
 */
public class VFichas extends javax.swing.JPanel {

    private static int cont = 0;
    /**
     * Creates new form VClientes
     */
    public VFichas() throws SQLException, ClassNotFoundException {
        initComponents();
        btnNotificar.setVisible(false);
        cargarDatos(0,1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListar = new javax.swing.JTable();
        btnAbrir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscarEliminados = new javax.swing.JButton();
        btnRestaurar = new javax.swing.JButton();
        txtDe = new com.toedter.calendar.JDateChooser();
        txtHasta = new com.toedter.calendar.JDateChooser();
        lblDe = new javax.swing.JLabel();
        lblHasta = new javax.swing.JLabel();
        btnFiltrar = new javax.swing.JButton();
        btnEnviarComprobantes = new javax.swing.JButton();
        btnEnviarReporte = new javax.swing.JButton();
        btnNotificar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnActivos = new javax.swing.JButton();
        btnEliminados = new javax.swing.JButton();
        btnMorosos = new javax.swing.JButton();
        btnGarantias = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 0, 18))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de registros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 0, 11))); // NOI18N

        btnBuscar.setBackground(new java.awt.Color(153, 255, 153));
        btnBuscar.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 102, 0));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault1.jpg"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(null);
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar.setIconTextGap(-3);
        btnBuscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault3.jpg"))); // NOI18N
        btnBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault2.jpg"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblListar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Folio", "Fecha", "Cliente", "Estado", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblListar);

        btnAbrir.setBackground(new java.awt.Color(153, 255, 153));
        btnAbrir.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        btnAbrir.setForeground(new java.awt.Color(0, 102, 0));
        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault1.jpg"))); // NOI18N
        btnAbrir.setText("Cargar");
        btnAbrir.setBorder(null);
        btnAbrir.setBorderPainted(false);
        btnAbrir.setContentAreaFilled(false);
        btnAbrir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbrir.setIconTextGap(-3);
        btnAbrir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault3.jpg"))); // NOI18N
        btnAbrir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault2.jpg"))); // NOI18N
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(153, 255, 153));
        btnEliminar.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(102, 0, 0));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDanger1.jpg"))); // NOI18N
        btnEliminar.setText("Anular");
        btnEliminar.setBorder(null);
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setIconTextGap(-3);
        btnEliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDanger3.jpg"))); // NOI18N
        btnEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDanger2.jpg"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscarEliminados.setBackground(new java.awt.Color(153, 255, 153));
        btnBuscarEliminados.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        btnBuscarEliminados.setForeground(new java.awt.Color(0, 102, 0));
        btnBuscarEliminados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault1.jpg"))); // NOI18N
        btnBuscarEliminados.setText("Buscar");
        btnBuscarEliminados.setBorder(null);
        btnBuscarEliminados.setBorderPainted(false);
        btnBuscarEliminados.setContentAreaFilled(false);
        btnBuscarEliminados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarEliminados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscarEliminados.setIconTextGap(-3);
        btnBuscarEliminados.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault3.jpg"))); // NOI18N
        btnBuscarEliminados.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault2.jpg"))); // NOI18N
        btnBuscarEliminados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEliminadosActionPerformed(evt);
            }
        });

        btnRestaurar.setBackground(new java.awt.Color(153, 255, 153));
        btnRestaurar.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        btnRestaurar.setForeground(new java.awt.Color(0, 102, 0));
        btnRestaurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault1.jpg"))); // NOI18N
        btnRestaurar.setText("Restaurar");
        btnRestaurar.setBorder(null);
        btnRestaurar.setBorderPainted(false);
        btnRestaurar.setContentAreaFilled(false);
        btnRestaurar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRestaurar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRestaurar.setIconTextGap(-3);
        btnRestaurar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault3.jpg"))); // NOI18N
        btnRestaurar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault2.jpg"))); // NOI18N
        btnRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarActionPerformed(evt);
            }
        });

        lblDe.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblDe.setText("DE");

        lblHasta.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblHasta.setText("HASTA");

        btnFiltrar.setBackground(new java.awt.Color(153, 255, 153));
        btnFiltrar.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        btnFiltrar.setForeground(new java.awt.Color(0, 102, 0));
        btnFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault1.jpg"))); // NOI18N
        btnFiltrar.setText("Filtrar");
        btnFiltrar.setBorder(null);
        btnFiltrar.setBorderPainted(false);
        btnFiltrar.setContentAreaFilled(false);
        btnFiltrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFiltrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFiltrar.setIconTextGap(-3);
        btnFiltrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault3.jpg"))); // NOI18N
        btnFiltrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault2.jpg"))); // NOI18N
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnEnviarComprobantes.setBackground(new java.awt.Color(153, 255, 153));
        btnEnviarComprobantes.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        btnEnviarComprobantes.setForeground(new java.awt.Color(0, 102, 0));
        btnEnviarComprobantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnMail1.jpg"))); // NOI18N
        btnEnviarComprobantes.setText("Enviar Correos");
        btnEnviarComprobantes.setBorder(null);
        btnEnviarComprobantes.setBorderPainted(false);
        btnEnviarComprobantes.setContentAreaFilled(false);
        btnEnviarComprobantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviarComprobantes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEnviarComprobantes.setIconTextGap(-3);
        btnEnviarComprobantes.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnMail3.jpg"))); // NOI18N
        btnEnviarComprobantes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnMail2.jpg"))); // NOI18N
        btnEnviarComprobantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarComprobantesActionPerformed(evt);
            }
        });

        btnEnviarReporte.setBackground(new java.awt.Color(153, 255, 153));
        btnEnviarReporte.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        btnEnviarReporte.setForeground(new java.awt.Color(0, 102, 0));
        btnEnviarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnMail1.jpg"))); // NOI18N
        btnEnviarReporte.setText("Enviar Reporte");
        btnEnviarReporte.setBorder(null);
        btnEnviarReporte.setBorderPainted(false);
        btnEnviarReporte.setContentAreaFilled(false);
        btnEnviarReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviarReporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEnviarReporte.setIconTextGap(-3);
        btnEnviarReporte.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnMail3.jpg"))); // NOI18N
        btnEnviarReporte.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnMail2.jpg"))); // NOI18N
        btnEnviarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarReporteActionPerformed(evt);
            }
        });

        btnNotificar.setBackground(new java.awt.Color(153, 255, 153));
        btnNotificar.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        btnNotificar.setForeground(new java.awt.Color(0, 102, 0));
        btnNotificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnMail1.jpg"))); // NOI18N
        btnNotificar.setText("Notificar");
        btnNotificar.setBorder(null);
        btnNotificar.setBorderPainted(false);
        btnNotificar.setContentAreaFilled(false);
        btnNotificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNotificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNotificar.setIconTextGap(-3);
        btnNotificar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnMail3.jpg"))); // NOI18N
        btnNotificar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnMail2.jpg"))); // NOI18N
        btnNotificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscarEliminados, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(btnAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnRestaurar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btnEnviarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(148, 148, 148))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(36, 36, 36)
                                    .addComponent(lblDe, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblHasta)
                                    .addGap(66, 66, 66)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnEnviarComprobantes, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtDe, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNotificar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnBuscarEliminados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbrir)
                    .addComponent(btnNotificar)
                    .addComponent(btnRestaurar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDe)
                    .addComponent(lblHasta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviarComprobantes)
                    .addComponent(btnEnviarReporte)
                    .addComponent(btnEliminar))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mostrar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 0, 11))); // NOI18N

        btnActivos.setBackground(new java.awt.Color(153, 255, 153));
        btnActivos.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        btnActivos.setForeground(new java.awt.Color(0, 102, 0));
        btnActivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault1.jpg"))); // NOI18N
        btnActivos.setText("Activos");
        btnActivos.setBorder(null);
        btnActivos.setBorderPainted(false);
        btnActivos.setContentAreaFilled(false);
        btnActivos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActivos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActivos.setIconTextGap(-3);
        btnActivos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault3.jpg"))); // NOI18N
        btnActivos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault2.jpg"))); // NOI18N
        btnActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivosActionPerformed(evt);
            }
        });

        btnEliminados.setBackground(new java.awt.Color(153, 255, 153));
        btnEliminados.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        btnEliminados.setForeground(new java.awt.Color(0, 102, 0));
        btnEliminados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault1.jpg"))); // NOI18N
        btnEliminados.setText("Eliminados");
        btnEliminados.setBorder(null);
        btnEliminados.setBorderPainted(false);
        btnEliminados.setContentAreaFilled(false);
        btnEliminados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminados.setIconTextGap(-3);
        btnEliminados.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault3.jpg"))); // NOI18N
        btnEliminados.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault2.jpg"))); // NOI18N
        btnEliminados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminadosActionPerformed(evt);
            }
        });

        btnMorosos.setBackground(new java.awt.Color(153, 255, 153));
        btnMorosos.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        btnMorosos.setForeground(new java.awt.Color(0, 102, 0));
        btnMorosos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnMail1.jpg"))); // NOI18N
        btnMorosos.setText("Morosos");
        btnMorosos.setBorder(null);
        btnMorosos.setBorderPainted(false);
        btnMorosos.setContentAreaFilled(false);
        btnMorosos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMorosos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMorosos.setIconTextGap(-3);
        btnMorosos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnMail3.jpg"))); // NOI18N
        btnMorosos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnMail2.jpg"))); // NOI18N
        btnMorosos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMorososActionPerformed(evt);
            }
        });

        btnGarantias.setBackground(new java.awt.Color(153, 255, 153));
        btnGarantias.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        btnGarantias.setForeground(new java.awt.Color(0, 102, 0));
        btnGarantias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnMail1.jpg"))); // NOI18N
        btnGarantias.setText("Garantias");
        btnGarantias.setBorder(null);
        btnGarantias.setBorderPainted(false);
        btnGarantias.setContentAreaFilled(false);
        btnGarantias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGarantias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGarantias.setIconTextGap(-3);
        btnGarantias.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnMail3.jpg"))); // NOI18N
        btnGarantias.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnMail2.jpg"))); // NOI18N
        btnGarantias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGarantiasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(btnActivos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGarantias, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnMorosos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminados, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnActivos)
                .addComponent(btnEliminados)
                .addComponent(btnMorosos)
                .addComponent(btnGarantias))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 489, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        try{
            if(txtBuscar.getText().length() < 1){
                cargarDatos(0,1);
                return;
            }
            int buscar = Integer.parseInt(txtBuscar.getText());
            buscarDatos(buscar,1);
            limpiarTextField();
        }catch(Exception e){
            try{
                buscarPalabra(txtBuscar.getText(),1);
            }catch(Exception e2){
                try {
                    cargarDatos(0,1);
                } catch (SQLException ex) {
                    Logger.getLogger(VFichas.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(VFichas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        
        String idFicha = "";
        try{
            int fila = tblListar.getSelectedRow();
            idFicha =  tblListar.getValueAt(fila, 0).toString();
            
            abrirFicha(idFicha);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un registro", "Seleccione un registro", JOptionPane.INFORMATION_MESSAGE);
        }
            
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        try{
            int fila = tblListar.getSelectedRow();
            int idFicha = (int) tblListar.getValueAt(fila, 0);
            FnFicha load = new FnFicha();
            Ficha temp = load.cargar(idFicha,1);
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea eliminar la ficha numero "+temp.getId()+"?");
            if(respuesta == JOptionPane.YES_OPTION){
                if(load.eliminar(idFicha)){
                    JOptionPane.showMessageDialog(null, "El registro ha sido eliminado", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(null, "No se pudo eliminar el registro", "Eliminar", JOptionPane.WARNING_MESSAGE);
                }
                cargarDatos(0,1);
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un registro en la tabla", "Seleccione", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivosActionPerformed
        try {
            cargarDatos(0,1);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error inesperado "+ex.getMessage(), "Cargar datos", JOptionPane.WARNING_MESSAGE);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error inesperado "+ex.getMessage(), "Cargar datos", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnActivosActionPerformed

    private void btnEliminadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminadosActionPerformed
        try {
            cargarDatos(-1,0);
            btnNotificar.setVisible(false);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error inesperado "+ex.getMessage(), "Cargar datos", JOptionPane.WARNING_MESSAGE);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error inesperado "+ex.getMessage(), "Cargar datos", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminadosActionPerformed

    private void btnBuscarEliminadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEliminadosActionPerformed

        try{
            if(txtBuscar.getText().length() < 1){
                cargarDatos(-1,0);
                return;
            }
            int buscar = Integer.parseInt(txtBuscar.getText());
            buscarDatos(buscar,0);
            limpiarTextField();
        }catch(Exception e){
            try{
                buscarPalabra(txtBuscar.getText(),0);
            }catch(Exception e2){
                try {
                    cargarDatos(-1,0);
                } catch (SQLException ex) {
                    Logger.getLogger(VFichas.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(VFichas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
        }
    }//GEN-LAST:event_btnBuscarEliminadosActionPerformed

    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed
        
        try{
            int fila = tblListar.getSelectedRow();
            int idFicha = (int) tblListar.getValueAt(fila, 0);
            FnFicha load = new FnFicha();
            Ficha temp = load.cargar(idFicha,0);
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea restaurar la ficha numero "+temp.getId()+"?");
            if(respuesta == JOptionPane.YES_OPTION){
                if(load.restaurar(idFicha)){
                    JOptionPane.showMessageDialog(null, "El registro ha sido restaurado", "Restaurar", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(null, "No se pudo restaurar el registro", "Restaurar", JOptionPane.WARNING_MESSAGE);
                }
                cargarDatos(-1,0);
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un registro en la tabla", "Seleccione", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnRestaurarActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        
        Date fecha1 = txtDe.getDate();
        Date fecha2 = txtHasta.getDate();
        btnEnviarComprobantes.setVisible(true);
        btnEnviarReporte.setVisible(true);
        FnFicha load = new FnFicha();
        try {
            llenarTabla(load.listarPorFecha(fecha1, fecha2), 1);
            
            limpiarTextField();
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Erros desconocido: "+ex.getMessage(),"Cargar Datos",JOptionPane.WARNING_MESSAGE);
        }
        
        
        
        
        
        btnRestaurar.setVisible(false);
        btnEliminar.setVisible(true);
        btnAbrir.setVisible(true);

        lblDe.setVisible(true);
        lblHasta.setVisible(true);
        txtDe.setVisible(true);
        txtHasta.setVisible(true);
        btnFiltrar.setVisible(true);

        btnBuscar.setVisible(true);
        btnBuscarEliminados.setVisible(false);
        
        
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnEnviarComprobantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarComprobantesActionPerformed
        
        Date fecha1 = txtDe.getDate();
        Date fecha2 = txtHasta.getDate();
        btnEnviarComprobantes.setVisible(true);
        FnFicha load = new FnFicha();
        
        
        try {
            limpiarTextField();
        } catch (SQLException ex) {
            Logger.getLogger(VFichas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VFichas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        btnRestaurar.setVisible(false);
        btnEliminar.setVisible(true);
        btnAbrir.setVisible(true);

        lblDe.setVisible(true);
        lblHasta.setVisible(true);
        txtDe.setVisible(true);
        txtHasta.setVisible(true);
        btnFiltrar.setVisible(true);

        btnBuscar.setVisible(true);
        btnBuscarEliminados.setVisible(false);
        
            
        
        try {
            load.enviarComprobantes(load.listarPorFecha(fecha1,fecha2));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error desconocido:"+ex.getMessage(),"Error",JOptionPane.WARNING_MESSAGE);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error desconocido:"+ex.getMessage(),"Error",JOptionPane.WARNING_MESSAGE);
        } catch (InterruptedException ex) {
            JOptionPane.showMessageDialog(null, "Error desconocido:"+ex.getMessage(),"Error",JOptionPane.WARNING_MESSAGE);
        }
        
        
        
        
    }//GEN-LAST:event_btnEnviarComprobantesActionPerformed

    private void btnEnviarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarReporteActionPerformed
        
        Date fecha1 = txtDe.getDate();
        Date fecha2 = txtHasta.getDate();
        btnEnviarComprobantes.setVisible(true);
        FnFicha load = new FnFicha();
        
        
        try {
            limpiarTextField();
        } catch (SQLException ex) {
            Logger.getLogger(VFichas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VFichas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        btnRestaurar.setVisible(false);
        btnEliminar.setVisible(true);
        btnAbrir.setVisible(true);

        lblDe.setVisible(true);
        lblHasta.setVisible(true);
        txtDe.setVisible(true);
        txtHasta.setVisible(true);
        btnFiltrar.setVisible(true);

        
        btnBuscar.setVisible(true);
        btnBuscarEliminados.setVisible(false);
        
            
        try {
            load.enviarReporte(fecha1,fecha2,load.listarPorFecha(fecha1,fecha2));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error desconocido:"+ex.getMessage(),"Error",JOptionPane.WARNING_MESSAGE);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error desconocido:"+ex.getMessage(),"Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEnviarReporteActionPerformed

    private void btnMorososActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMorososActionPerformed
        
        btnNotificar.setVisible(true);
        
        btnAbrir.setVisible(true);
        
        btnFiltrar.setVisible(true);
        btnEliminar.setVisible(true);
        btnRestaurar.setVisible(false);
        txtDe.setVisible(true);
        txtHasta.setVisible(true);
        
        FnFicha load = new FnFicha();
        try {
            llenarTabla(load.morosos(), 1);
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error inesperado: "+ex.getMessage(),"Cargar morosos",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnMorososActionPerformed

    private void btnNotificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificarActionPerformed
        
        Date fecha1 = txtDe.getDate();
        Date fecha2 = txtHasta.getDate();
        FnFicha load = new FnFicha();
        
        
        try {
            limpiarTextField();
        } catch (SQLException ex) {
            Logger.getLogger(VFichas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VFichas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            
        try {
            load.enviarNotificacion(load.morosos());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error desconocido:"+ex.getMessage(),"Error",JOptionPane.WARNING_MESSAGE);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error desconocido:"+ex.getMessage(),"Error",JOptionPane.WARNING_MESSAGE);
        } catch (InterruptedException ex) {
            JOptionPane.showMessageDialog(null, "Error desconocido:"+ex.getMessage(),"Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnNotificarActionPerformed

    private void btnGarantiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGarantiasActionPerformed
        
        btnNotificar.setVisible(false);
        
        btnAbrir.setVisible(true);
        
        btnFiltrar.setVisible(true);
        btnEliminar.setVisible(true);
        btnRestaurar.setVisible(false);
        txtDe.setVisible(true);
        txtHasta.setVisible(true);
        
        FnFicha load = new FnFicha();
        try {
            llenarTabla(load.garantias(), 1);
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error inesperado: "+ex.getMessage(),"Cargar morosos",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnGarantiasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnActivos;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarEliminados;
    private javax.swing.JButton btnEliminados;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEnviarComprobantes;
    private javax.swing.JButton btnEnviarReporte;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnGarantias;
    private javax.swing.JButton btnMorosos;
    private javax.swing.JButton btnNotificar;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDe;
    private javax.swing.JLabel lblHasta;
    private javax.swing.JTable tblListar;
    private javax.swing.JTextField txtBuscar;
    private com.toedter.calendar.JDateChooser txtDe;
    private com.toedter.calendar.JDateChooser txtHasta;
    // End of variables declaration//GEN-END:variables

    
    private void cargarDatos(int listar, int estado) throws SQLException, ClassNotFoundException {
        btnEnviarComprobantes.setVisible(false);
        btnEnviarReporte.setVisible(false);
        limpiarTextField();
        if(listar == -1){//eliminados
            btnRestaurar.setVisible(true);
            btnEliminar.setVisible(false);
            btnAbrir.setVisible(false);
            btnBuscar.setVisible(false);
            
            lblDe.setVisible(false);
            lblHasta.setVisible(false);
            txtDe.setVisible(false);
            txtHasta.setVisible(false);
            btnFiltrar.setVisible(false);
            
            
            btnBuscarEliminados.setVisible(true);
            estado=0;
        }else{
            btnRestaurar.setVisible(false);
            btnEliminar.setVisible(true);
            btnAbrir.setVisible(true);
            
            lblDe.setVisible(true);
            lblHasta.setVisible(true);
            txtDe.setVisible(true);
            txtHasta.setVisible(true);
            btnFiltrar.setVisible(true);
            
            btnBuscar.setVisible(true);
            btnBuscarEliminados.setVisible(false);
        }
            
        FnFicha datbd= new FnFicha();
        llenarTabla(datbd.listar(listar,estado), estado);
        
    }

    

    private void buscarDatos(int buscar, int i) throws SQLException, ClassNotFoundException {
        
        FnFicha load= new FnFicha();
        llenarTabla(load.listar(buscar, i), i);
        
    }
    
    private void llenarTabla(ArrayList<Ficha> lista, int i){
        DefaultTableModel modelo;
        modelo = new DefaultTableModel() {
           @Override
           public boolean isCellEditable(int fila, int columna) {
               return false; //Con esto conseguimos que la tabla no se pueda editar
           }
        };
        
        modelo.addColumn("Folio");
        modelo.addColumn("Fecha");
        modelo.addColumn("Cliente");
        modelo.addColumn("Estado");
        modelo.addColumn("Total");
        tblListar.setModel(modelo);
        FnFicha datbd= new FnFicha();
        int cont =0;
        try{
            for (Ficha temp : lista) {
                int descuento =0;
                if(temp.getDescuento().getPorcetange() > 0){
                    descuento = (temp.getValorTotal()*temp.getDescuento().getPorcetange())/100;
                    temp.setValorTotal(temp.getValorTotal()-descuento);
                }
                Object[] fila = new Object[5];
                fila[0] = temp.getId();
                fila[1] = temp.getFecha();
                fila[2] = temp.getCliente().getNombre();
                if(temp.getEstado() == 1)
                    fila[3] = "Pendiente";
                if(temp.getEstado() == 2)
                    fila[3] = "Pagada";
                if(temp.getEstado() == 3)
                    fila[3] = "Despachada";
                if(temp.getEstado() == 0)
                    fila[3] = "Anulada";
                if(temp.getEstado() == 4)
                    fila[3] = "Garantia";
                fila[4] = "$ "+temp.getValorTotal();
                modelo.addRow(fila);
            }
            tblListar.updateUI();
            if(tblListar.getRowCount() == 0){
                JOptionPane.showMessageDialog(null, "No se encontraron resultados, pruebe con otros valores de búsqueda.");
                 
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error, ["+e.getMessage()+"]");
        }
    }

    private void limpiarTextField() throws SQLException, ClassNotFoundException {
        txtBuscar.setText("");
    }

    private void abrirFicha(String idFicha) throws SQLException, ClassNotFoundException {
        Boton btn = new Boton();
        btn.abrirFicha(idFicha);
    }

    private void buscarPalabra(String buscar, int estado) throws SQLException, ClassNotFoundException {
        
        FnFicha load= new FnFicha();
        llenarTabla(load.listarPorPalabra(buscar,estado), estado);
        
    }

    

    

    
    
}
