/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entities.Ficha;
import entities.User;
import fn.Boton;
import fn.FnFicha;
import fn.FnUser;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author home
 */
public class VMostrarFichas extends javax.swing.JPanel {
    
    Boton boton = new Boton();
    FnFicha load = new FnFicha();
    TableRowSorter trs;
    DefaultTableModel modelo = new DefaultTableModel() {
           @Override
           public boolean isCellEditable(int fila, int columna) {
               return false; //Con esto conseguimos que la tabla no se pueda editar
           }
        };
        
        
    
    
    
    /**
     * Creates new form VClientes
     */
    public VMostrarFichas() throws SQLException, ClassNotFoundException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListar = new javax.swing.JTable();
        btnAbrir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRestaurar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnActivos = new javax.swing.JButton();
        btnEliminados = new javax.swing.JButton();
        btnMorosos = new javax.swing.JButton();
        btnGarantias = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblDe = new javax.swing.JLabel();
        txtDe = new com.toedter.calendar.JDateChooser();
        lblHasta = new javax.swing.JLabel();
        txtHasta = new com.toedter.calendar.JDateChooser();
        btnFiltrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtDe1 = new com.toedter.calendar.JDateChooser();
        txtHasta1 = new com.toedter.calendar.JDateChooser();
        lblDe1 = new javax.swing.JLabel();
        lblHasta1 = new javax.swing.JLabel();
        btnEnviarReporte = new javax.swing.JButton();
        btnEnviarComprobantes = new javax.swing.JButton();
        btnExportarExcel = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 0, 18))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de registros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 0, 11))); // NOI18N

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });

        tblListar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Folio", "Fecha", "Cliente", "Estado", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblListar);

        btnAbrir.setBackground(new java.awt.Color(153, 255, 153));
        btnAbrir.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        btnAbrir.setForeground(new java.awt.Color(0, 102, 0));
        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault1.jpg"))); // NOI18N
        btnAbrir.setText("Cargar");
        btnAbrir.setBorder(null);
        btnAbrir.setBorderPainted(false);
        btnAbrir.setContentAreaFilled(false);
        btnAbrir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbrir.setIconTextGap(-3);
        btnAbrir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault3.jpg"))); // NOI18N
        btnAbrir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault2.jpg"))); // NOI18N
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(153, 255, 153));
        btnEliminar.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(102, 0, 0));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDanger1.jpg"))); // NOI18N
        btnEliminar.setText("Anular");
        btnEliminar.setBorder(null);
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setIconTextGap(-3);
        btnEliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDanger3.jpg"))); // NOI18N
        btnEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDanger2.jpg"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnRestaurar.setBackground(new java.awt.Color(153, 255, 153));
        btnRestaurar.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        btnRestaurar.setForeground(new java.awt.Color(0, 102, 0));
        btnRestaurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault1.jpg"))); // NOI18N
        btnRestaurar.setText("Restaurar");
        btnRestaurar.setBorder(null);
        btnRestaurar.setBorderPainted(false);
        btnRestaurar.setContentAreaFilled(false);
        btnRestaurar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRestaurar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRestaurar.setIconTextGap(-3);
        btnRestaurar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault3.jpg"))); // NOI18N
        btnRestaurar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault2.jpg"))); // NOI18N
        btnRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Buscar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRestaurar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbrir)
                    .addComponent(btnRestaurar)
                    .addComponent(btnEliminar)))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mostrar todos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 0, 11))); // NOI18N

        btnActivos.setBackground(new java.awt.Color(153, 255, 153));
        btnActivos.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        btnActivos.setForeground(new java.awt.Color(0, 102, 0));
        btnActivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault1.jpg"))); // NOI18N
        btnActivos.setText("Activos");
        btnActivos.setBorder(null);
        btnActivos.setBorderPainted(false);
        btnActivos.setContentAreaFilled(false);
        btnActivos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActivos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActivos.setIconTextGap(-3);
        btnActivos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault3.jpg"))); // NOI18N
        btnActivos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault2.jpg"))); // NOI18N
        btnActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivosActionPerformed(evt);
            }
        });

        btnEliminados.setBackground(new java.awt.Color(153, 255, 153));
        btnEliminados.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        btnEliminados.setForeground(new java.awt.Color(0, 102, 0));
        btnEliminados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault1.jpg"))); // NOI18N
        btnEliminados.setText("Eliminados");
        btnEliminados.setBorder(null);
        btnEliminados.setBorderPainted(false);
        btnEliminados.setContentAreaFilled(false);
        btnEliminados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminados.setIconTextGap(-3);
        btnEliminados.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault3.jpg"))); // NOI18N
        btnEliminados.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault2.jpg"))); // NOI18N
        btnEliminados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminadosActionPerformed(evt);
            }
        });

        btnMorosos.setBackground(new java.awt.Color(153, 255, 153));
        btnMorosos.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        btnMorosos.setForeground(new java.awt.Color(0, 102, 0));
        btnMorosos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnMail1.jpg"))); // NOI18N
        btnMorosos.setText("Morosos");
        btnMorosos.setBorder(null);
        btnMorosos.setBorderPainted(false);
        btnMorosos.setContentAreaFilled(false);
        btnMorosos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMorosos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMorosos.setIconTextGap(-3);
        btnMorosos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnMail3.jpg"))); // NOI18N
        btnMorosos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnMail2.jpg"))); // NOI18N
        btnMorosos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMorososActionPerformed(evt);
            }
        });

        btnGarantias.setBackground(new java.awt.Color(153, 255, 153));
        btnGarantias.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        btnGarantias.setForeground(new java.awt.Color(0, 102, 0));
        btnGarantias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnMail1.jpg"))); // NOI18N
        btnGarantias.setText("Garantias");
        btnGarantias.setBorder(null);
        btnGarantias.setBorderPainted(false);
        btnGarantias.setContentAreaFilled(false);
        btnGarantias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGarantias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGarantias.setIconTextGap(-3);
        btnGarantias.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnMail3.jpg"))); // NOI18N
        btnGarantias.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnMail2.jpg"))); // NOI18N
        btnGarantias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGarantiasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(btnActivos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGarantias, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMorosos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminados, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnActivos)
                .addComponent(btnEliminados)
                .addComponent(btnMorosos)
                .addComponent(btnGarantias))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fechas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Script", 0, 11))); // NOI18N

        lblDe.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblDe.setText("DE");

        lblHasta.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblHasta.setText("HASTA");

        btnFiltrar.setBackground(new java.awt.Color(153, 255, 153));
        btnFiltrar.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        btnFiltrar.setForeground(new java.awt.Color(0, 102, 0));
        btnFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault1.jpg"))); // NOI18N
        btnFiltrar.setText("Filtrar");
        btnFiltrar.setBorder(null);
        btnFiltrar.setBorderPainted(false);
        btnFiltrar.setContentAreaFilled(false);
        btnFiltrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFiltrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFiltrar.setIconTextGap(-3);
        btnFiltrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault3.jpg"))); // NOI18N
        btnFiltrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnDefault2.jpg"))); // NOI18N
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDe, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDe, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHasta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnFiltrar)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblHasta, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtHasta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDe, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reportes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 0, 11))); // NOI18N

        lblDe1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblDe1.setText("DE");

        lblHasta1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblHasta1.setText("HASTA");

        btnEnviarReporte.setBackground(new java.awt.Color(153, 255, 153));
        btnEnviarReporte.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        btnEnviarReporte.setForeground(new java.awt.Color(0, 102, 0));
        btnEnviarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnMail1.jpg"))); // NOI18N
        btnEnviarReporte.setText("Enviar Reporte");
        btnEnviarReporte.setBorder(null);
        btnEnviarReporte.setBorderPainted(false);
        btnEnviarReporte.setContentAreaFilled(false);
        btnEnviarReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviarReporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEnviarReporte.setIconTextGap(-3);
        btnEnviarReporte.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnMail3.jpg"))); // NOI18N
        btnEnviarReporte.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnMail2.jpg"))); // NOI18N
        btnEnviarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarReporteActionPerformed(evt);
            }
        });

        btnEnviarComprobantes.setBackground(new java.awt.Color(153, 255, 153));
        btnEnviarComprobantes.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        btnEnviarComprobantes.setForeground(new java.awt.Color(0, 102, 0));
        btnEnviarComprobantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnMail1.jpg"))); // NOI18N
        btnEnviarComprobantes.setText("Enviar Correos");
        btnEnviarComprobantes.setBorder(null);
        btnEnviarComprobantes.setBorderPainted(false);
        btnEnviarComprobantes.setContentAreaFilled(false);
        btnEnviarComprobantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviarComprobantes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEnviarComprobantes.setIconTextGap(-3);
        btnEnviarComprobantes.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnMail3.jpg"))); // NOI18N
        btnEnviarComprobantes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnMail2.jpg"))); // NOI18N
        btnEnviarComprobantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarComprobantesActionPerformed(evt);
            }
        });

        btnExportarExcel.setBackground(new java.awt.Color(153, 255, 153));
        btnExportarExcel.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        btnExportarExcel.setForeground(new java.awt.Color(0, 102, 0));
        btnExportarExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnMail1.jpg"))); // NOI18N
        btnExportarExcel.setText("Exportar");
        btnExportarExcel.setBorder(null);
        btnExportarExcel.setBorderPainted(false);
        btnExportarExcel.setContentAreaFilled(false);
        btnExportarExcel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExportarExcel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExportarExcel.setIconTextGap(-3);
        btnExportarExcel.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnMail3.jpg"))); // NOI18N
        btnExportarExcel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonGraph/btnMail2.jpg"))); // NOI18N
        btnExportarExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblDe1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDe1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(lblHasta1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHasta1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnEnviarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(btnEnviarComprobantes, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(btnExportarExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtDe1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDe1)
                            .addComponent(lblHasta1)))
                    .addComponent(txtHasta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviarComprobantes)
                    .addComponent(btnEnviarReporte)
                    .addComponent(btnExportarExcel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        
        String idFicha = "";
        try{
            int fila = tblListar.getSelectedRow();
            idFicha =  tblListar.getValueAt(fila, 0).toString();
            abrirFicha(idFicha);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un registro", "Seleccione un registro", JOptionPane.INFORMATION_MESSAGE);
        }
            
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        try{
            int fila = tblListar.getSelectedRow();
            int idFicha = (int) tblListar.getValueAt(fila, 0);
            FnFicha load = new FnFicha();
            Ficha temp = load.cargar(idFicha,1);
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea eliminar la ficha numero "+temp.getId()+"?");
            if(respuesta == JOptionPane.YES_OPTION){
                if(load.eliminar(idFicha)){
                    boton.fichas(load.listar(0, 1));
                    JOptionPane.showMessageDialog(null, "El registro ha sido eliminado", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(null, "No se pudo eliminar el registro", "Eliminar", JOptionPane.WARNING_MESSAGE);
                }
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un registro en la tabla", "Seleccione", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivosActionPerformed
        try {
            boton.fichas(load.listar(0, 1));
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Ha ocurrodo un error al cargar los datos: "+ex.getMessage(),"Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnActivosActionPerformed

    private void btnEliminadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminadosActionPerformed
        FnFicha load = new FnFicha();
        if(load.validarAdmin()){
            try {
                boton.fichas(load.listar(-1, 0));
            } catch (SQLException | ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Error al cargar los datos: "+ex.getMessage(),"Error",JOptionPane.WARNING_MESSAGE);
            }
        }
            
    }//GEN-LAST:event_btnEliminadosActionPerformed

    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed
        
        try{
            int fila = tblListar.getSelectedRow();
            int idFicha = (int) tblListar.getValueAt(fila, 0);
            
            Ficha temp = load.cargar(idFicha,0);
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea restaurar la ficha numero "+temp.getId()+"?");
            if(respuesta == JOptionPane.YES_OPTION){
                if(load.restaurar(idFicha)){
                    boton.fichas(load.listar(-1, 0));
                    JOptionPane.showMessageDialog(null, "El registro ha sido restaurado", "Restaurar", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(null, "No se pudo restaurar el registro", "Restaurar", JOptionPane.WARNING_MESSAGE);
                }
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un registro en la tabla", "Seleccione", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnRestaurarActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        
        Date fecha1 = txtDe.getDate();
        Date fecha2 = txtHasta.getDate();
        
        FnFicha load = new FnFicha();
        try {
            boton.fichas(load.listarPorFecha(fecha1, fecha2));
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error desconocido: "+ex.getMessage(),"Cargar Datos",JOptionPane.WARNING_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnEnviarComprobantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarComprobantesActionPerformed
        
        Date fecha1 = txtDe1.getDate();
        Date fecha2 = txtHasta1.getDate();
        
        FnFicha load = new FnFicha();
        
        
        try {
            load.enviarComprobantes(load.listarPorFecha(fecha1,fecha2));
        } catch (SQLException | ClassNotFoundException | InterruptedException ex) {
            JOptionPane.showMessageDialog(null, "Error desconocido:"+ex.getMessage(),"Error",JOptionPane.WARNING_MESSAGE);
        }
        
        
        
        
    }//GEN-LAST:event_btnEnviarComprobantesActionPerformed

    private void btnEnviarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarReporteActionPerformed
        
        Date fecha1 = txtDe1.getDate();
        Date fecha2 = txtHasta1.getDate();
        
        FnFicha load = new FnFicha();
        
        try {
            load.enviarReporte(fecha1,fecha2,load.listarPorFecha(fecha1,fecha2));
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error desconocido:"+ex.getMessage(),"Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEnviarReporteActionPerformed

    private void btnMorososActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMorososActionPerformed
        
        try {
            boton.fichas(load.morosos());
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error inesperado: "+ex.getMessage(),"Cargar morosos",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnMorososActionPerformed

    private void btnGarantiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGarantiasActionPerformed
        
        
        try {
            boton.fichas(load.garantias());
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error inesperado: "+ex.getMessage(),"Cargar morosos",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnGarantiasActionPerformed

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        
        
        txtBuscar.addKeyListener(new KeyAdapter() {

            @Override
            public void keyReleased(final KeyEvent e) {
//                trs.setRowFilter(RowFilter.regexFilter(txtBuscar.getText(), 1));
                trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscar.getText(), 0,1,2,3,4,5,7,8,9,10));
            }
            
        });
        
        
        
        trs = new TableRowSorter(modelo);
        
        tblListar.setRowSorter(trs);
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void btnExportarExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarExcelActionPerformed
        Date fecha1 = txtDe1.getDate();
        Date fecha2 = txtHasta1.getDate();
        
        FnFicha load = new FnFicha();
        try {
            load.exportarExcel(load.listarPorFecha(fecha1,fecha2));
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Error: "+ex.getMessage(),"Error",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnExportarExcelActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnActivos;
    private javax.swing.JButton btnEliminados;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEnviarComprobantes;
    private javax.swing.JButton btnEnviarReporte;
    private javax.swing.JButton btnExportarExcel;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnGarantias;
    private javax.swing.JButton btnMorosos;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDe;
    private javax.swing.JLabel lblDe1;
    private javax.swing.JLabel lblHasta;
    private javax.swing.JLabel lblHasta1;
    private javax.swing.JTable tblListar;
    private javax.swing.JTextField txtBuscar;
    private com.toedter.calendar.JDateChooser txtDe;
    private com.toedter.calendar.JDateChooser txtDe1;
    private com.toedter.calendar.JDateChooser txtHasta;
    private com.toedter.calendar.JDateChooser txtHasta1;
    // End of variables declaration//GEN-END:variables

    
    public void cargarDatos(ArrayList<Ficha> lista) throws SQLException, ClassNotFoundException {
        modelo.addColumn("Folio");
        modelo.addColumn("Fecha");
        modelo.addColumn("Cliente");
        modelo.addColumn("Correo");
        modelo.addColumn("Telefono");
        modelo.addColumn("Comuna");
        modelo.addColumn("Ciudad");
        modelo.addColumn("Estado");
        modelo.addColumn("Total");
        modelo.addColumn("Saldo");
        modelo.addColumn("Vendedor");
        tblListar.setModel(modelo);
        
        llenarTabla(lista);
        
    }

    
    private void llenarTabla(ArrayList<Ficha> lista){
        FnFicha datbd= new FnFicha();
        int cont =0;
        try{
            for (Ficha temp : lista) {
                int descuento =0;
                if(temp.getDescuento().getPorcetange() > 0){
                    descuento = (temp.getValorTotal()*temp.getDescuento().getPorcetange())/100;
                    temp.setValorTotal(temp.getValorTotal()-descuento);
                }
                Object[] fila = new Object[11];
                fila[0] = temp.getId();
                fila[1] = temp.getFecha();
                fila[2] = temp.getCliente().getNombre();
                fila[3] = temp.getCliente().getEmail();
                fila[4] = temp.getCliente().getTelefono();
                fila[5] = temp.getCliente().getComuna();
                fila[6] = temp.getCliente().getCiudad();
                if(temp.getEstado() == 1)
                    fila[7] = "Pendiente";
                if(temp.getEstado() == 2)
                    fila[7] = "Pagada";
                if(temp.getEstado() == 3)
                    fila[7] = "Despachada";
                if(temp.getEstado() == 0){
                    fila[7] = "Anulada";
                    cont++;
                }
                if(temp.getEstado() == 4)
                    fila[7] = "Garantia";
                fila[8] = "$ "+temp.getValorTotal();
                fila[9] = "$ "+temp.getSaldo();
                fila[10] = temp.getUser().getNombre();
                
                modelo.addRow(fila);
            }
            if(cont > 0){
                btnRestaurar.setVisible(true);
                btnEliminar.setVisible(false);
                btnAbrir.setVisible(false);
            }else{
                btnRestaurar.setVisible(false);
                btnEliminar.setVisible(true);
                btnAbrir.setVisible(true);
            }
            tblListar.updateUI();
            if(tblListar.getRowCount() == 0){
                JOptionPane.showMessageDialog(null, "No se encontraron resultados, pruebe con otros valores de búsqueda.");
                 
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error, ["+e.getMessage()+"]");
        }
    }


    private void abrirFicha(String idFicha) throws SQLException, ClassNotFoundException {
        Boton btn = new Boton();
        btn.abrirFicha(idFicha);
    }

    

    

    

    

    
    
}
